services:
  #nginx:
  #  image: nginx:stable
  #  container_name: nginx
  #  ports:
  #    - 8080:80
  #  volumes:
  #    - "./njs:/etc/nginx/njs"
  #    # - "./nginx.conf:/etc/nginx/nginx.conf"
  #    #- "./default.conf:/etc/nginx/conf.d/default.conf"
  #    - "./default1.conf:/etc/nginx/nginx.conf"
  #    - "./upstreams:/etc/nginx/upstreams"
  #    # - "./pics/:/usr/share/nginx/html/pics/"
  nginx-lb:
    image: nginx:stable
    container_name: nginx-lb
    ports:
     - 8080:80
    # network_mode: host
    volumes:
      - "./default2.conf:/etc/nginx/nginx.conf"
      - "./njs:/etc/nginx/njs"
      - "./upstreams:/etc/nginx/upstreams"
        #- "./default-1:/etc/nginx/conf.d/default.conf"
        #- "./pics/:/usr/share/nginx/html/pics/"
  # nginx-1:
  #   image: nginx:stable
  #   container_name: nginx-1
  
  # nginx-2:
  #   image: nginx:stable
  #   container_name: nginx-2

  # nginx-3:
  #   image: nginx:stable
  #   container_name: nginx-3    