services:

  load_balancer:
    image: nginx:stable
    container_name: nginx-lb
    ports:
     - 8080:80
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./njs:/etc/nginx/njs"
    # image: docker.angie.software/angie:latest
    # container_name: angie-lb
    # ports:
    #  - 8080:80
    # volumes:
    #   - "./angie.conf:/etc/angie/angie.conf"
    #   - "./njs:/etc/angie/njs"

    networks:
      custom_net:
        ipv4_address: 10.5.0.5

  nginx-1:
    image: nginx:stable
    container_name: nginx-1
    networks:
      custom_net:
        ipv4_address: 10.5.0.2
  
  nginx-2:
    image: nginx:stable
    container_name: nginx-2
    networks:
      custom_net:
        ipv4_address: 10.5.0.3

  nginx-3:
    image: nginx:stable
    container_name: nginx-3
    networks:
      custom_net:
        ipv4_address: 10.5.0.4


networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1    